CREATE TABLE T_STUDENT (
  SID     VARCHAR2(10) PRIMARY KEY,
  NAME    VARCHAR2(10) NOT NULL,
  SEX     VARCHAR2(1)  NOT NULL CHECK (SEX IN ('F', 'M')),
  ID_CARD VARCHAR2(19) NOT NULL,
  EMAIL   VARCHAR2(20),
  ADDRESS VARCHAR2(50) NOT NULL
);
CREATE SEQUENCE STUDENT_SEQ START WITH 1445200001;

CREATE TABLE T_TEACHER (
  TID     VARCHAR2(6) PRIMARY KEY,
  NAME    VARCHAR2(10) NOT NULL,
  SEX     VARCHAR2(1)  NOT NULL CHECK (SEX IN ('F', 'M')),
  ID_CARD VARCHAR2(19) NOT NULL,
  EMAIL   VARCHAR2(20),
  ADDRESS VARCHAR2(50) NOT NULL
);
CREATE SEQUENCE TEACHER_SEQ START WITH 144001;

CREATE TABLE T_SUBJECT (
  ID   VARCHAR2(3) PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL,
  TID  VARCHAR2(6)  NOT NULL REFERENCES T_TEACHER (TID),
  INFO VARCHAR2(50) NOT NULL
);
DROP TABLE T_SUBJECT;
CREATE SEQUENCE SUBJECT_SEQ START WITH 100;

CREATE TABLE T_SCORE (
  SID   VARCHAR2(10) REFERENCES T_STUDENT (SID),
  ID    VARCHAR2(3) REFERENCES T_SUBJECT (ID),
  SCORE NUMBER(3) NOT NULL,
  PRIMARY KEY (SID, ID)
);


SELECT * FROM T_STUDENT;