SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID FROM EMPLOYEES;

SELECT FIRST_NAME||' '|| LAST_NAME NAME FROM EMPLOYEES;

SELECT EMPLOYEE_ID, DEPARTMENT_ID, DEPARTMENT_NAME
  FROM EMPLOYEES NATURAL JOIN DEPARTMENTS;

SELECT EMPLOYEE_ID, FIRST_NAME, D.DEPARTMENT_ID, DEPARTMENT_NAME
  FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT USERS_SEQ.currval FROM dual;